databases:
  - name: fashionworld_db
    plan: free
    databaseName: designer_wears
    user: onyiebaby

services:
  - type: web
    plan: free
    name: fashionworld
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn fashionworld.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fashionworld_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4